version: '3.1'

services:
  clientui-microservice:
    image: clientui-microservice
    build:
      context: clientui
      dockerfile: Dockerfile
    container_name: clientui-microservice
    ports:
      - 8080:8080
    environment:
      - patient.service.url=http://patient-microservice:8081
      - history.service.url=http://history-microservice:8082
    networks:
      - web-server-bridge
    depends_on:
      - patient-microservice
      - history-microservice

  patient-microservice:
    image: patient-microservice
    build:
      context: patient
      dockerfile: Dockerfile
    restart: on-failure
    container_name: patient-microservice
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/patientdb?useSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": "Makong57",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
    }'
    networks:
      - web-server-bridge
    depends_on:
      - patient-mysql-db

  history-microservice:
    image: history-microservice
    build:
      context: history
      dockerfile: Dockerfile
    restart: on-failure
    container_name: history-microservice
    ports:
      - 8082:8082
    environment:
      - SPRING_DATA_MONGODB_HOST=docker-mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=history-db
      - SPRING_DATA_MONGODB_USERNAME=rootuser
      - SPRING_DATA_MONGODB_PASSWORD=rootpass
    networks:
      - web-server-bridge
    depends_on:
      - history-mongo-db

  patient-mysql-db:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Makong57
      - MYSQL_DATABASE=patientdb
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web-server-bridge

  history-mongo-db:
    image: mongo
    container_name: docker-mongo
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=history-db
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - web-server-bridge


volumes:
  db-data: {}

networks:
  web-server-bridge:
    driver: bridge