patient:
  service:
    url: http://localhost:8081

history:
  service:
    url: http://localhost:8082

assessment:
  service:
    url: http://localhost:8083

server:
  error:
    whitelabel:
      enabled: false